### PR TITLE
Adopt to Sia 1.4.7

### PR DESCRIPTION
**Pull request by chrsch**
This PR provides fixes to use Siasync with Sia 1.4.7

### CODE REVIEW

**Comment by tbenz9** [comment]
Hey @chrsch great to hear from you and thanks for submitting this!  Have you got a screenshot or asciinema showing it works with 1.4.7?  I really need to get some automated testing for Siasync but I'm not quite there yet...

**Comment by chrsch** [comment]
Hi @tbenz9, I'll provide a video or asciinema, not yet sure what illustrates in a nicer way. Also, I will update this PR so siasync will also properly support empty directories ;-)

**Comment by capusta** [comment]
```
root@0c8ab15a5972:/src# make
go build -o siasync *.go
# command-line-arguments
./main.go:147:16: cannot use *address (type string) as type client.Options in argument to client.New
make: *** [Makefile:10: build] Error 2
root@0c8ab15a5972:/src# go version
go version go1.14.2 linux/amd64
```
Is there a standard way of building I'm missing ?
Thank you.

**Comment by chrsch** [comment]
@tbenz9 
- Updated to fully support Sia directories now. 
- Also, added command-line option to not ignore hidden files (which are now ignored)
- Still had no time to do a asciinema, but running this build for almost a week now on my sync node and it works like a charm
- I must admit I didn't update the tests - first need to figure out why the used mocking technique no longer seems to work

@capusta It's pretty much the way to build it. Or simply "go build".

**Comment by capusta** [comment]
```
root@51d21a0fba08:/src# make dependencies
go get -u github.com/sirupsen/logrus
go get -u gitlab.com/NebulousLabs/Sia/node/api/client
go get -u github.com/fsnotify/fsnotify
go get -u gitlab.com/NebulousLabs/Sia/modules
go get -u gitlab.com/NebulousLabs/Sia/build
root@51d21a0fba08:/src# echo $?
0
root@51d21a0fba08:/src# git log -1 --format=format:%H
1a59025b4d2bde9584b3b1ae557df8af0e687de0
root@51d21a0fba08:/src# go build
# _/src
./main.go:149:16: cannot use *address (type string) as type client.Options in argument to client.New
root@51d21a0fba08:/src# echo $?
2
root@51d21a0fba08:/src# make
go build -o siasync *.go
# command-line-arguments
./main.go:149:16: cannot use *address (type string) as type client.Options in argument to client.New
make: *** [Makefile:10: build] Error 2
root@51d21a0fba08:/src# echo $?
2
root@51d21a0fba08:/src# go version
go version go1.14.2 linux/amd64
root@51d21a0fba08:/src# echo $GOPATH
/go
root@51d21a0fba08:/src# ls /go
bin  pkg  src
root@51d21a0fba08:/src# ls /go/pkg/*/*
/go/pkg/linux_amd64/github.com:
fsnotify  sirupsen

/go/pkg/linux_amd64/gitlab.com:
NebulousLabs
```
i hope im not being fancy here
```
on my mac> git log -1 --format=format:%H
1a59025b4d2bde9584b3b1ae557df8af0e687de0
```
and i hope im not running those fancy commands from a non-documented env.
`docker run -v $(pwd):/src -ti golang:1.14.2  bash`

**Comment by chrsch** [comment]
@capusta Tried it using docker and it works also well for me (running cmd from the repository dir)

`docker run --rm -v "$PWD":/usr/src/siasync -w /usr/src/siasync golang:1.14 make dependencies && go build -v`

**Comment by tbenz9** [comment]
Thank you so much for these improvements!  Let me do a little testing and I'll roll a new release with your name on it.

**Comment by capusta** [comment]
we-e-e-i-r-d.
```
~/siasync$ docker run --rm -v "$PWD":/usr/src/siasync -w /usr/src/siasync golang:1.14 sh -c "make dependencies; make"
go get -u github.com/sirupsen/logrus
go get -u gitlab.com/NebulousLabs/Sia/node/api/client
go get -u github.com/fsnotify/fsnotify
go get -u gitlab.com/NebulousLabs/Sia/modules
go get -u gitlab.com/NebulousLabs/Sia/build
go build -o siasync *.go
# command-line-arguments
./main.go:149:16: cannot use *address (type string) as type client.Options in argument to client.New
make: *** [Makefile:10: build] Error 2
```
well ... either one i guess ...
```
 docker run --rm -v "$PWD":/usr/src/siasync -w /usr/src/siasync golang:1.14 sh -c "make dependencies; go build -v"
go get -u github.com/sirupsen/logrus
go get -u gitlab.com/NebulousLabs/Sia/node/api/client
go get -u github.com/fsnotify/fsnotify
go get -u gitlab.com/NebulousLabs/Sia/modules
go get -u gitlab.com/NebulousLabs/Sia/build
_/usr/src/siasync
# _/usr/src/siasync
./main.go:149:16: cannot use *address (type string) as type client.Options in argument to client.New
```

**Comment by chrsch** [comment]
@capusta eventually I found the error when compiling arm64 binaries. I provided a fix to compile with Sia v1.4.8 here https://github.com/vcomtec/siasync master branch. PR here will follow.

**Pull request merged**
